name: changesets

on:
  push:
    branches:
    - "**"

jobs:
  changesets:
    name: changesets
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout Repo"
      uses: actions/checkout@v3

    - name: "Setup pnpm 10"
      uses: pnpm/action-setup@v2
      with:
        version: 10.15.0

    - name: "Setup Node.js 24"
      uses: actions/setup-node@v3
      with:
        node-version: 24.7.0
        cache: "pnpm"

    - name: "Install Dependencies"
      run: pnpm install --frozen-lockfile

    - name: "Create Changesets Pull Request"
      uses: changesets/action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
